apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: taxi
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ0YXhpYXBwMjYwOS5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiVm1WdWEyRjBPbFpsYm10aGRFQTRNall4IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
